/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "f84e47d12c46a056675153cfea62af3453740ad1"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
