/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_
#define GPU_WEBGPU_DAWN_COMMIT_HASH_H_

#define DAWN_COMMIT_HASH "79144ddd23dd5f9431e250fccbec78b896e4cebe"

#endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_
